import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Passport Documentation",
  description: "Generated by Advanced Backend in RC School",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-gradient-to-tr from-gray-700 via-gray-900 to-black ${inter.className}`}>{children}</body>
    </html>
  );
}
